name: PlunaMC-Island
version: 1.0
author: Kevloe
api-version: 1.19
main: de.plunamc.island.PlunaIsland
depend:
  - PlunaAPI
commands:
  is:
  spawn:
  warzone:
  updateborder:
  bits:
  build:
  warp:
  warps: